version: '3'

services:

  group-exercise:
    depends_on:
      - docker-mysql
    platform: linux/x86_64
    build:
      context: .
      args:
        JAR_FILE: group-exercise.jar
    ports:
      - "8010:8010"
    networks:
      - default
    environment:
      logging.level.org.springframework: INFO
      server.port: 8010
      spring.profiles.active: local
      # Not secure but works for now - allowPublicKeyRetrieval
      spring.datasource.url: jdbc:mysql://docker-mysql:3306/product?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      spring.datasource.username: motive
      spring.datasource.password: team_a

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://docker-mysql:3306/product?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true -user=motive -password=team_a -connectRetries=60 migrate -locations=filesystem:/flyway/sql/src
    volumes:
      - .:/flyway/sql
    depends_on:
      - docker-mysql

  docker-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
      MYSQL_USER: motive
      MYSQL_PASSWORD: team_a

volumes:
  repo:
    driver: local
