version: '3'

services:

  group-exercise:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: group-exercise.jar
    ports:
      - "8010:8010"
    networks:
      - default
    environment:
      logging.level.org.springframework: INFO
      server.port: 8010
      spring.profiles.active: local

volumes:

  cache:
    driver: local
